name: release

on:
  push:
    branches:
      - main

jobs:
  test:
    uses: ErgoFriend/cf-to-dynamodb-schema/.github/workflows/test.yml@main

  build-and-release:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Set .npmrc
        run: echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
      # prepare npm run
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - name: install dependencies
        run: npm ci
      # run scripts
      - name: run build
        run: npm run build
      # release-it
      - name: Major release
        id: major
        run: npm run release major --ci
        if: contains(toJSON(github.event.commits.*.message), 'bump up version major')
      - name: Minor release
        id: minor
        run: npm run release minor --ci
        if: steps.major.conclusion == 'skipped' && contains(toJSON(github.event.commits.*.message), 'bump up version minor')
      - name: Patch release
        run: npm run release patch --ci
        if: "!(steps.major.conclusion == 'success' || steps.minor.conclusion == 'success')"
