name: test

on:
  push:
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # prepare npm run
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - name: install dependencies
        run: npm ci
      # run scripts
      - name: run test
        run: npm run test
